### ISSUE TITLE
Custom HTTP Headers

### ISSUE THREAD

**Issue by cemalgnlts** [sintaxi/surge#503] opened 2023-04-11 12:25 UTC
Hello I would like to know if there is a way to add a custom http header.

I want to add these titles but I don't think there is a way.
```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

**Comment by ezra-obiwale** [comment] 2023-05-29 10:25
Duplicate of https://github.com/sintaxi/surge/issues/165

**Closed** 2023-05-29 15:56 UTC
