### ISSUE TITLE
Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency

### ISSUE THREAD

**Issue by matheus-moreira** [sintaxi/surge#448] opened 2021-04-09 17:07 UTC
Node: v15.13.0

When i run "surge" it gives me this message:

``Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency (Use `node --trace-warnings ...` to show where the warning was created)``

If I'm trying to login for the first time the process gets stuck and I'm forced to abort.

**Comment by sintaxi** [comment] 2021-04-09 18:30
I'm unable to recreate this issue even when running with `--trace-warnings`. I'm on node `v15.13.0` and surge `v0.23.0` and MacOS Catalina `v10.15.3` .  Let me know if you have any suggestions.

**Comment by matheus-moreira** [comment] 2021-04-09 18:46
i really dont know =/

but whatever you did, fixed it.

**Comment by sintaxi** [comment] 2021-04-09 20:07
Ok great. I've tested on both `latest` and `edge` so I'm going to close this ticket. Thanks for opening this ticket.

**Closed by sintaxi** 2021-04-09 20:07 UTC

**Comment by fu-sen** [comment] 2021-04-10 01:18
The `surge` CLI has been updated, Try:
```
npm i -g surge
```

You also had to be aware of the existence of https://github.com/sintaxi/surge/issues/439 . 
If you have login problems, you need to reopen and publish a little more details.

**Comment by fu-sen** [comment] 2021-04-10 02:37
Maybe you're just starting out with Surge because you're trying to log in?
In that case, Discussions is the ideal place to post, as your operation is likely to be causing trouble and not a bug:
https://github.com/sintaxi/surge/discussions

**Comment by sintaxi** [comment] 2021-04-10 02:39
@fu-sen I think @matheus-moreira no longer has the problem.

**Comment by fu-sen** [comment] 2021-04-10 02:44
@sintaxi You probably overlooked:

> If I'm trying to login for the first time the process gets stuck and I'm forced to abort.

There is no other report, so I touched on the details.

**Comment by sintaxi** [comment] 2021-04-10 02:49
Hmm, Perhaps I'm misunderstanding but there was an update which includes the following...

> but whatever you did, fixed it.

Thats why closed the issue. If you think I misinterpreted the response feel free to reopen the ticket.

**Comment by matheus-moreira** [comment] 2021-04-10 03:00
hey guys, just to clarify: there was a small update that fixed the issue (i reported directly to sintaxi before opening the issue).

i highly appreciate your attention.

**Comment by sintaxi** [comment] 2021-04-10 03:03
Great. Thanks for clearing that up and thanks to both of you for helping make surge better. I'm very grateful to people like you who take the time to report issues and test fixes.

**Comment by wonius** [comment] 2022-07-30 12:38
logout and login
