### ISSUE TITLE
"surge --add" user not working

### ISSUE THREAD

**Issue by owendall** [sintaxi/surge#237] opened 2016-11-22 19:57 UTC
I have tried this on multiple projects.   Posted also to Slack.

Example:

`$ surge --add owendall@agile-innovations.net`

while within the root of my project.

**Comment by sintaxi** [comment] 2016-12-08 00:43
Our system seems to have blocked your email address because the emails were bouncing. Could it be a MX record issue with your DNS?

**Comment by davidguttman** [comment] 2017-01-10 15:23
Also having an issue with this:

```
⚡ surge --add user@domain.io

    Surge - surge.sh

              email: david@guttman.io
              token: *****************
       project path: /blog/dist/
               size: 279 files, 12.0 MB
             domain: domain.com
             upload: [====================] 100%, eta: 0.0s
   propagate on CDN: [====                ] 20% /assets/font/material-design-icons/Material-Desi
               plan: Free
              users: david@guttman.io
         IP Address: 45.55.110.124

    Success! Project is published and running at domain.com
```

**Comment by dmiotti** [comment] 2017-01-11 20:34
Same here `surge --add <email>` is just deploying the current directory.

**Comment by hugozap** [comment] 2017-02-14 18:41
This feature is not working. Tried with -a and --a

**Comment by ryandeussing** [comment] 2017-02-27 19:32
It would be great if this feature worked. You might also consider restricting this feature to paid plans, which would be great for Surge.

**Comment by yoursoftwarebug** [comment] 2017-04-19 00:02
Confirmed, it is not working.
Tried "surge --add em@il' and "surge --add em@il --domain test.surge.sh".

**Comment by proxyusertryingsurge** [comment] 2017-06-07 01:25
Yeah, tried it and it's not working, but advertised this on their website.

**Comment by sintaxi** [comment] 2017-06-07 09:49
I just tested. It works for me. I ran..

```
surge . --add brock@chloi.io
```
An invite is emailed to brock@chloi that has to accept publishing rights.

**Comment by sintaxi** [comment] 2017-06-07 09:50
I should add that I think this was broken a while back and it got patched. Apologies for not closing this issue. Will do better.

**Closed by sintaxi** 2017-06-07 09:50 UTC

**Comment by RedTn** [comment] 2017-11-17 00:58
@sintaxi I was checking with a co-worker, we had the same issue even though the email was being sent but when we do "surge list" it wasn't showing he had access.

But, we did determine it was because the emails are case-sensitive :(

**Comment by cdunlap** [comment] 2018-02-22 05:58
Is this supposed to re-deploy the project again? That's all this does for me. Looking at the instructions on https://surge.sh/help/adding-collaborators it doesn't seem very clear whether or not it is supposed to completely re-deploy everything. Simply running `surge --add <email address>` produces prompts for the project and the domain again, just like an initial deployment. If I supply those in the command line as arguments the process does not prompt, but it doesn't seem to add a collaborator either. It feels very broken.

**Comment by dideler** [comment] 2018-06-11 17:24
Also not working for us with v0.20.1.

```
surge --add <email>
```

It prompts for the project directory. Then it prompts for the domain. Then it uploads docs.

It's been about 15 minutes and the invited user hasn't received an email yet.
When they view the domains they have access to (`surge --list`), the new one doesn't show.

Not sure if it's working and delayed, broken, or I'm using it incorrectly.

**Comment by Luttos** [comment] 2018-11-15 00:34
> I just tested. It works for me. I ran..
> 
> ```
> surge . --add brock@chloi.io
> ```
> An invite is emailed to brock@chloi that has to accept publishing rights.

Worked for me

**Comment by kylebakerio** [comment] 2020-05-21 20:34
it is confusing that this looks like a normal deploy, which is exactly what it would look like if this argument were completely broken and ignored, and which means that you must use the correct deploy folder in this command.

So, for more clarity, explaining that, and/or giving an example of:

`surge public-folder example-domain.com -add sharewithuser@email.com`

Just putting this here for future readers.

Result is you sharewithuser@email.com gets an email, they have to accept, and then everything works.

Note that this must be done for each individual subdomain as well.

**Comment by sintaxi** [comment] 2020-05-22 19:44
I totally understand the confusion and difficultly dealing with this api. You will be happy to hear this is has been addressed and in the next release of surge you will be able to add/remove people to your project with a `surge invite` and `surge revoke` command (which doesn't deploy your project).

To invite people to your project...

```
surge invite example.com user1@email.com user2@email.com user3@email.com
```

To remove people from your project...

```
surge revoke example.com user1@email.com user2@email.com user3@email.com
```

The work has already been done and is on deck for release. Let me know if you see any issues with this approach.

**Comment by kylebakerio** [comment] 2020-05-27 05:08
Oh, excellent. I had heard generalized fear that perhaps this project was dead, but I've now been a huge fan of surge for years and am delighted to hear a new update is coming. Any other place we can get interesting news and follow what's planned for the next release?

As for this, yeah, that sounds much more explicit. Will there be a way to list who currently has these permissions?

**Comment by thathurtabit** [comment] 2021-02-22 17:01
I'm using `"surge": "^0.21.7"` and when I try:

```
surge invite my-surge-address.surge.sh user@mycompany.com
```

I get the error: `Aborted - No such file or directory: invite`
