### ISSUE TITLE
Cryptic error message on CLI

### ISSUE THREAD

**Issue by guioconnor** [sintaxi/surge#314] opened 2018-03-09 00:46 UTC
Sorry if this is documented somewhere, I couldn't find any relevant reference to this problem.

Since today, my Travis build has been failing to deploy with the message below, I tried to do a local deploy from my machine and the same happened. After logging out and trying to log back in I get this error when I attempt to login, so I'm currently logged out on the CLI.

```/Users/guioconnor/.nvm/versions/node/v8.9.4/lib/node_modules/surge/lib/middleware/util/helpers.js:146
      if (e) throw e
             ^

Error: certificate has expired
    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:637:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
```

**Comment by nk1tz** [comment] 2018-03-09 01:11
duplicate of [313](https://github.com/sintaxi/surge/issues/313)

**Comment by sintaxi** [comment] 2018-03-09 05:26
Resolved.

**Closed by sintaxi** 2018-03-09 05:26 UTC
