### ISSUE TITLE
deployments with domain containing capital letters

### ISSUE THREAD

**Issue by dstack** [sintaxi/surge#174] opened 2015-12-29 20:34 UTC
deployments of a domain containing capital letters are reported as deployed to the lowercase version of the same domain by the command line tool, however, the deployment is not made (or is incomplete) and visiting that domain produces the "Project Not Found" page.

example:
  project-WIP.surge.sh -> deploys as project-wip.surge.sh, but page is not available.

The command-line tool take this into account, but somewhere the mapping is getting lost, and the deployment is either incomplete or not there at all.

**Comment by dbachrach** [comment] 2016-01-08 22:20
+1, these capitalized domains are also listed in `surge list`, but cannot be turndown with `surge teardown`.

**Comment by kennethormandy** [comment] 2016-01-12 20:26
Thanks for opening an issue and sorry for the trouble, this is actually a duplicate of #127 we’re aware of. If it happens on a project with Surge Plus, just [get in touch](https://surge.sh/help/chat) and we’ll take care of it. Otherwise, we’ll post in that other issue when it’s fixed, if you want to subscribe to it, so you can teardown those projects too.

**Closed by kennethormandy** 2016-01-12 20:26 UTC
Labels: duplicate
